[build]
  Command = "yarn run build"
  functions = "out_functions"
  publish   = "out_publish"
  ignore = "git log --oneline -1 | grep 'Update dependency @types/'"

[build.environment]
  YARN_FLAGS = "--pure-lockfile --verbose"
