version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: status message
          command: "echo building ... dashboard:$CIRCLE_SHA1 ."
      - run:
          name: env
          command: env
      - run:
          name: npm run test
          command: "echo npm run test:circleci"
      - run:
          name: env
          command: "docker build -t dashboard:$CIRCLE_SHA1 ."
      - run:
          name: integration test
          command: |
            docker run -d -p 3000:3000 dashboard:$CIRCLE_SHA1
            cont=$(docker ps -ql)
            sleep 5
            wget -T 30 --tries=10 -S -v --retry-connrefused http://localhost:3000 -O- && RESULT=$?
            docker logs $cont
            exit $RESULT

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
