version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: status message
          command: "echo building ... dashboard:$CIRCLE_SHA1 ."
      - run:
          name: env
          command: env
      - run:
          name: npm run test
          command: "echo npm run test:circleci"
      - run:
          name: npm run lint
          command: "echo npm run test:circleci"
      - run:
          name: docker build
          command: "docker build -t dashboard:$CIRCLE_SHA1 ."
      - run:
          name: integration test of generated docker image
          command: |
            CONT_NAME=dashboard-$CIRCLE_SHA1
            docker run -d --name $CONT_NAME -p 3000:3000 dashboard:$CIRCLE_SHA1
            cont=$(docker ps -ql)
            sleep 5
            #
            # docker-compose will start 2 containers, the one with service will be named `contacts`
            # we start another container with curl in the same network as `contacts`, this way we have
            # all exposed ports from `contacts` available on `localhost` in this new container
            docker run --network container:$CONT_NAME \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/  
            #&& RESULT=$?
            docker logs $cont
            exit $RESULT

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
