name: 'unit tests'
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unitTest" ?!
  unitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run Jest
      # You may pin to the exact commit or the version.
      # uses: stefanoeb/jest-action@f9bb23f509cde20ee9b494f0496d1d3323861cc4
      uses: stefanoeb/jest-action@1.0.4
    - name: Jest Annotations & Coverage
      # You may pin to the exact commit or the version.
      # uses: mattallty/jest-github-action@43bbcd073fa43a927322f188220b6592acae003b
      uses: mattallty/jest-github-action@v1.0.3
